feat(docker compose): adding a environment for development.
convenia/Pigeon pull request #280
Opened 2022-05-19 20:04 UTC by TarsisioXavier

# The Problem
When cloning this project the developer doesn't have all the dependencies to start coding.

# Solution
This feature contains a docker compose file which is going to provide the container to handle the php calls and a RabbitMQ serve to run the tests suites.

# Testing
- Checkout the branch `feature/docker-environment`;
- Inside the project run `docker-compose build --no-cache --pull`;
- After that, run `docker-compose up -d`;
- Then run `docker exec -ti pigeon sh`, that should put you inside the container;
- Inside the container run `composer install`;
- Finally, run `./vendor/bin/phpunit` and that's it;

2022-05-20 19:03 UTC, jleonardolemos requested changes
Nice contribution!! Running tests in local environment is clumsy today and this PR will get this easier!!!

2022-05-25 21:14 UTC, TarsisioXavier commented on Dockerfile
> +&& docker-php-ext-install -j$(nproc) gd sockets fileinfo dom tokenizer xml simplexml
Resolved on https://github.com/convenia/Pigeon/pull/280/commits/7fe7923c5cf630dbe9bceeee4c4e8ad7c9bfddab

2022-05-31 17:22 UTC, jleonardolemos commented
@TarsisioXavier Can you fix the pipeline?

2022-08-06 13:31 UTC, TarsisioXavier commented
> @TarsisioXavier Can you fix the pipeline?

Sry to keep you waiting. Pipeline it's fixed :)

2022-08-07 23:22 UTC, merged